from simulator import *
from example_dfa import *

def test_even_and_my_name():
    dfa_u = intersect(even_chars, my_name)
    assert not dfa_u.accepted([1,2,3,4,5,6], trace=True)
    assert not dfa_u.accepted([], trace=True)
    assert not dfa_u.accepted([1,2], trace=True)
    assert dfa_u.accepted("FABRIZIO", trace=True)
    assert dfa_u.accepted("FABRIZIOFABRIZIO", trace=True)
    assert dfa_u.accepted("FABRIZIOFABRIZIOFABRIZIO", trace=True)
    assert not dfa_u.accepted("fabrizio", trace=True)
    assert not dfa_u.accepted("FABRIZIOFABR", trace=True)
    assert not dfa_u.accepted([1], trace=True)
    assert not dfa_u.accepted("not my name", trace=True)
    assert not dfa_u.accepted("Fab", trace=True)
    assert not dfa_u.accepted("0", trace=True)
    assert not dfa_u.accepted("Dj Hi-Tek", trace=True)
    assert not dfa_u.accepted("Fabri", trace=True)

def test_even_chars_and_divisible_by_3():
    dfa_u = intersect(even_chars, divisible_by_3)
    assert dfa_u.accepted(['1','2','3','4','5','6'], trace=True)
    assert dfa_u.accepted([], trace=True)
    assert dfa_u.accepted(['1','2'], trace=True)
    assert dfa_u.accepted(str(654321), trace=True)
    assert dfa_u.accepted([], trace=True)
    assert dfa_u.accepted(str(543210), trace=True)
    assert not dfa_u.accepted(['2','2'], trace=True)
    assert not dfa_u.accepted(['1','2','3'], trace=True)
    assert not dfa_u.accepted(['1','2','3','4','5'], trace=True)
    assert not dfa_u.accepted(['5','5'], trace=True)
    assert not dfa_u.accepted(list(range(8)), trace=True)
    assert not dfa_u.accepted(['1','3'], trace=True)

def test_traffic_light_and_substring101():
    dfa_u = intersect(traffic_light, substring_101)
    assert dfa_u.accepted([0, 0, 0, 0, 1, 1, 1, 2, 1, 0, 0, 0] , trace=True)
    assert dfa_u.accepted([0, 0, 0, 0, 1, 1, 1, 2, 1] , trace=True)
    assert dfa_u.accepted([0, 0, 0, 0, 1, 1, 1, 2, 1, 0, 0, 0,1,2] , trace=True)
    assert not dfa_u.accepted([0, 0, 0, 0, 1, 1, 1, 2] , trace=True)
    assert not dfa_u.accepted([1, 1, 2, 2], trace=True)
    assert not dfa_u.accepted([0]*2000, trace=True)
    assert dfa_u.accepted([1, 0, 1], trace=True)
    assert dfa_u.accepted([1, 0, 1] + [1, 0]*10, trace=True)
    assert dfa_u.accepted([0] * 10 + [1, 0, 1], trace=True)
    assert not dfa_u.accepted([], trace=True)
    assert dfa_u.accepted([1, 0, 1], trace=True)
    assert dfa_u.accepted([1, 1, 1, 0, 1], trace=True)

def test_traffic_light_and_all_1s():
    dfa_u = intersect(traffic_light, binary_string_all_1)
    assert not dfa_u.accepted([0, 0, 0, 0, 1, 1, 1, 2, 1, 0, 0, 0] , trace=True)
    assert not dfa_u.accepted([0, 0, 0, 0, 1, 1, 1, 2, 1] , trace=True)
    assert not dfa_u.accepted([0, 0, 0, 0, 1, 1, 1, 2, 1, 0, 0, 0,1,2] , trace=True)
    assert not dfa_u.accepted([0, 1], trace=True)
    assert not dfa_u.accepted([0, 0, 0, 0, 1, 1, 1, 2] , trace=True)
    assert not dfa_u.accepted([1, 1, 2, 2], trace=True)
    assert not dfa_u.accepted([0]*2000, trace=True)
    assert dfa_u.accepted([1,1,1,1,1,1,1,1], trace=True)
    assert dfa_u.accepted([1]*25, trace=True)
    assert dfa_u.accepted([1], trace=True)
    assert not dfa_u.accepted([], trace=True)
    assert not dfa_u.accepted([1]*5 + [0,2], trace=True)


def test_substring_101_and_strictly_alternating():
    dfa_u = intersect(substring_101, strictly_alternating)
    assert dfa_u.accepted([1, 0, 1,0], trace=True)
    assert dfa_u.accepted([1, 0] + [1, 0]*10, trace=True)
    assert not dfa_u.accepted([0] * 10 + [1, 0, 1], trace=True)
    assert not dfa_u.accepted([], trace=True)
    assert dfa_u.accepted([1, 0, 1, 0], trace=True)
    assert not dfa_u.accepted([1, 1, 1, 0, 0, 0, 1], trace=True)
    assert dfa_u.accepted([1, 0] * 5, trace=True)
    assert dfa_u.accepted([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], trace=True)
    assert not dfa_u.accepted([1, 0], trace=True)
    assert not dfa_u.accepted([], trace=True)
    assert not dfa_u.accepted([1, 1], trace=True)
    assert not dfa_u.accepted([1, 0, 1], trace=True)


def test_divisible_by_3_and_first_last_x():
    dfa_u = intersect(divisible_by_3, first_and_last_char_is_x)
    assert not dfa_u.accepted(['3'], trace=True)
    assert not dfa_u.accepted(['1','5'], trace=True)
    assert not dfa_u.accepted(str(10), trace=True)
    assert not dfa_u.accepted(str(23), trace=True)
    assert not dfa_u.accepted(['1','2'], trace=True)
    assert not dfa_u.accepted(['5', '1', '0', '1'], trace=True)
    assert not dfa_u.accepted('x', trace=True)
    assert not dfa_u.accepted('xx', trace=True)
    assert not dfa_u.accepted('xasdafkshfkajdx', trace=True)
    assert not dfa_u.accepted('xa', trace=True)
    assert not dfa_u.accepted('xxxxxxxxxxa', trace=True)
    assert not dfa_u.accepted([], trace=True)

def test_string_all_1_and_strictly_alternating():
    dfa_u = intersect(binary_string_all_1, strictly_alternating) 
    assert not dfa_u.accepted([1,1,1,1,1,1,1,1], trace=True)
    assert not dfa_u.accepted([1]*25, trace=True)
    assert not dfa_u.accepted([1], trace=True)
    assert not dfa_u.accepted([], trace=True)
    assert not dfa_u.accepted([0, 1], trace=True)
    assert not dfa_u.accepted([1]*5 + [0], trace=True)
    assert not dfa_u.accepted([1, 0] * 5, trace=True)
    assert not dfa_u.accepted([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], trace=True)
    assert not dfa_u.accepted([1, 0], trace=True)
    assert not dfa_u.accepted([], trace=True)
    assert not dfa_u.accepted([1, 1], trace=True)
    assert not dfa_u.accepted([1, 0, 1], trace=True)

def test_at_least_3_and_is_weekend():
    dfa_u = intersect(at_least_3, is_weekend)
    assert not dfa_u.accepted("onetwothree", trace=True)
    assert not dfa_u.accepted([1, 2, 3], trace=True)
    assert not dfa_u.accepted(["hello", "my", "name", "is", "three"], trace=True)
    assert not dfa_u.accepted([], trace=True)
    assert not dfa_u.accepted([1], trace=True)
    assert not dfa_u.accepted([1, 2], trace=True)
    assert dfa_u.accepted(["Saturday","Saturday","Saturday"], trace=True)
    assert dfa_u.accepted(["Saturday", "Sunday", "Saturday", "Sunday"], trace=True)
    assert dfa_u.accepted(["Sunday","Sunday","Sunday","Sunday"], trace=True)
    assert not dfa_u.accepted([], trace=True)
    assert not dfa_u.accepted(["Monday"], trace=True)
    assert dfa_u.accepted(["Saturday"] * 5, trace=True)

def test_at_least_3_and_loooong():
    dfa_u = intersect(at_least_3, loooong)
    assert not dfa_u.accepted("onetwothree", trace=True)
    assert not dfa_u.accepted([1, 2, 3], trace=True)
    assert not dfa_u.accepted("sm", trace=True)
    assert not dfa_u.accepted([], trace=True)
    assert not dfa_u.accepted([1], trace=True)
    assert not dfa_u.accepted([1, 2], trace=True)
    assert dfa_u.accepted("lo0o0o0o0o0ong", trace=True)
    assert dfa_u.accepted("lOOOOOOOOOO000000000o0o0o0o0o0ng", trace=True)
    assert dfa_u.accepted("long", trace=True)
    assert not dfa_u.accepted("short", trace=True)
    assert not dfa_u.accepted("smol", trace=True)
    assert not dfa_u.accepted("MINISCULE", trace=True)

def test_at_least_3_and_all_1():
    dfa_u = intersect(at_least_3, binary_string_all_1)
    assert dfa_u.accepted([1,1,1,1,1,1,1,1], trace=True)
    assert dfa_u.accepted([1]*25, trace=True)
    assert dfa_u.accepted([1]*500, trace=True)
    assert not dfa_u.accepted([], trace=True)
    assert not dfa_u.accepted([0, 1], trace=True)
    assert not dfa_u.accepted([2]*2, trace=True)
    assert not dfa_u.accepted("onetwothree", trace=True)
    assert not dfa_u.accepted([1, 2, 3], trace=True)
    assert not dfa_u.accepted(["hello", "my", "name", "is", "three"], trace=True)
    assert not dfa_u.accepted([], trace=True)
    assert not dfa_u.accepted([3], trace=True)
    assert not dfa_u.accepted([1, 2], trace=True)


def test_capitalized_and_loooong():
    dfa_u = intersect(capitalized_first_letter_only, loooong)
    assert dfa_u.accepted("Long", trace=True)
    assert dfa_u.accepted("Looong", trace=True)
    assert dfa_u.accepted("Looooong", trace=True)
    assert dfa_u.accepted("Lo0o0o0o0o0ong", trace=True)
    assert not dfa_u.accepted("Lamb", trace=True)
    assert not dfa_u.accepted("AA", trace=True)
    assert not dfa_u.accepted("aaaaaaT", trace=True)
    assert not dfa_u.accepted("AmericA", trace=True)
    assert not dfa_u.accepted("LOOOOOOOOOO000000000o0o0o0o0o0ng", trace=True)
    assert not dfa_u.accepted("ShorT", trace=True)
    assert not dfa_u.accepted("smol", trace=True)
    assert not dfa_u.accepted("MINISCULE", trace=True)

def test_capitalized_and_my_name():
    dfa_u = intersect(capitalized_first_letter_only, my_name)
    assert not dfa_u.accepted("Matthew", trace=True)
    assert not dfa_u.accepted("Fabrizio", trace=True)
    assert not dfa_u.accepted("A", trace=True)
    assert not dfa_u.accepted("AA", trace=True)
    assert not dfa_u.accepted("aaaaaaT", trace=True)
    assert not dfa_u.accepted("AmericA", trace=True)
    assert not dfa_u.accepted("FABRIZIO", trace=True)
    assert not dfa_u.accepted("FABRIZIOFABRIZIO", trace=True)
    assert not dfa_u.accepted("FABRIZIOFABRIZIOFABRIZIO", trace=True)
    assert not dfa_u.accepted("fabrizio", trace=True)
    assert not dfa_u.accepted("FABRIZIOFABR", trace=True)
    assert not dfa_u.accepted("not my name", trace=True)



